### ISSUE TITLE
'install' directory is not removed

### ISSUE THREAD

**Issue by kbeaugrand** [centreon/centreon#6258]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**: 2.8.22

**Centreon Engine version**: 1.8.1

**Centreon Broker version**: 3.0.14

**OS**: Centos 7.4

**Additional environment details (AWS, VirtualBox, physical, etc.): Running on Docker
Image availiable on docker hub: kbeaugrand/centreon-central
Source code availiable at kbeaugrand/centreon-central on github

**Steps to reproduce the issue:**
1. Write your docker-compose.yml
```yml
version: '3'
services: 
  centreon-central:
  image: kbeaugrand/centreon-central
  privileged: true
    environment:
      - PHP_DATE_TIMEZONE=Europe/Paris
    links: 
      - db:db
    ports: 
      - "8080:80"
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
  db:
    image: mariadb
    environment: 
      - MYSQL_ROOT_PASSWORD=my-secret-pw
```

2.Start your stack
```sh
docker-compose up -d
```
3. Follow installation wizard on centreon's servers pages:
https://documentation.centreon.com/docs/centreon/en/2.8.x/installation/from_iso.html#via-the-web-interface

**Describe the results you received:**
The wizard is looping in upgrade mode.

**Describe the results you expected:**
The login screen must be displayed.

**Additional information you think important (e.g. issue happens only occasionally):**
In my mind, the installation dir under /usr/share/centreon/www/ must be removed after installation process. 
After having deleted it, the centreon's central seems to work.
