### ISSUE TITLE
Impossible to install on CentOS 7

### ISSUE THREAD

**Issue by MiStErLu** [centreon/centreon#6998]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**: 
   Last version from repository
**Centreon Engine version**: 
   Last version from repository
**Centreon Broker version**: 
   Last version from reposity
**OS**: 
    CentOS 7
**Additional environment details (AWS, VirtualBox, physical, etc.):**
    KVM

**Steps to reproduce the issue:**
   Here is the Ansible Script to install.

```
# defaults file for centreon-central
pkgs_centreon:
  - centreon-base-config-centreon-engine
  - centreon
  - MariaDB-server
  - MySQL-python


---
# tasks file for centreon-central
- name: "Install the yum centreon repository"
  yum:
    name: "http://yum.centreon.com/standard/3.4/el7/stable/noarch/RPMS/centreon-release-3.4-4.el7.centos.noarch.rpm"
    state: present
    disable_gpg_check: yes


- name: "Install the centreon base package"
  package:
    name: "{{ pkgs_centreon }}"
    state: present


- name: "Create a file for timezone for php"
  file:
    path: "/etc/php.d/php-timezone.ini"
    state: touch

- name: "Add default timezone for centreon"
  lineinfile:
    path: "/etc/php.d/php-timezone.ini"
    regexp: '^date'
    line: 'date.timezone = Europe/Paris'

- name: "Create a folder for MariaDB settings"
  file:
    path: "/etc/systemd/system/mariadb.service.d/limits.conf"
    state: touch

- name: "Add LimitNOFILE for Maria"
  lineinfile:
    path: "/etc/php.d/php-timezone.ini"
    regexp: '^LimitNOFILE'
    line: 'LimitNOFILE=32000'

- name: "Add LimitNOFILE for Maria"
  lineinfile:
    path: "/etc/php.d/php-timezone.ini"
    regexp: '^[Service]'
    line: '[Service]'

- name: Check if root password is set
  shell: >
    mysqladmin -u root status
  changed_when: false
  failed_when: false
  register: root_pwd_check
  tags: mariadb

- name: Set MariaDB root password for the first time (root@localhost)
  mysql_user:
    name: root
    password: "{{ mariadb_root_password }}"
    host: localhost
    state: present
  when: root_pwd_check.rc == 0
  tags: mariadb

- name: Set MariaDB root password for 127.0.0.1, ::1
  mysql_user:
    name: root
    password: "{{ mariadb_root_password }}"
    host: "{{ item }}"
    login_user: root
    login_password: "{{ mariadb_root_password }}"
    state: present
  with_items:
    - ::1
    - 127.0.0.1
  when: root_pwd_check.rc == 0
  tags: mariadb

- name: "Disabled Firewalld"
  service:
    name: firewalld
    state: stopped
    enabled: no

- name: "Enable httpd service"
  service:
    name: httpd
    state: started
    enabled: yes
- name: "Enable MariaDB service"
  service:
    name: mariadb
    state: started
    enabled: yes
```
I go to my favorite web browser
And when i setup web install i am block here :

![erreur centreon](https://user-images.githubusercontent.com/5516692/48947343-1c2dce00-ef31-11e8-840b-f9e19a677d29.png)

And when i go to httpd log i got this 

```
[Fri Nov 23 14:42:37.930725 2018] [:error] [pid 19731] [client XXXXXXXXX:52062] PHP Notice:  Undefined index: BROKER_MODULE in /usr/share/centreon/www/install/steps/process/process_step4.php on line 39, referer: http://YYYYYYYYYYY/centreon/install/setup.php
[Fri Nov 23 14:58:58.646442 2018] [:error] [pid 19734] [client XXXXXXXXXXX:52268] PHP Warning:  mysql_connect(): Headers and client library minor version mismatch. Headers:50556 Library:100119 in /usr/share/centreon/www/install/steps/functions.php on line 52, referer: http://YYYYYYYYYYY/centreon/install/setup.php
[Fri Nov 23 14:58:58.881946 2018] [:error] [pid 19734] [client XXXXXXXXXXX:52268] PHP Warning:  mysql_connect(): Headers and client library minor version mismatch. Headers:50556 Library:100119 in /usr/share/centreon/www/install/steps/functions.php on line 52, referer: http://YYYYYYYYYYY/centreon/install/setup.php

```

**Describe the results you received:**
Nothing appear of screen

**Describe the results you expected:**
Centreon should install...

**Additional information you think important (e.g. issue happens only occasionally):**
